Explicitly define $dbType for default MySQL config
The `helper.php` checks for the `dbType` property on the 
`Config` class. Since nothing is defined it throws:

```
Fatal error: Access to undeclared static property: 
Config::$dbType in …/Quill/lib/helpers.php on line 3
```